// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDSUvHaAVlrbAt2xrRuS4G-9wZbmXj-uE',
    appId: '1:650977751393:web:a40a872f50c14ce7bed520',
    messagingSenderId: '650977751393',
    projectId: 'hediety-3d6a8',
    authDomain: 'hediety-3d6a8.firebaseapp.com',
    databaseURL: 'https://hediety-3d6a8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hediety-3d6a8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUoMdqVBubP5JiYT1nX1YcoHbyIjytB3o',
    appId: '1:650977751393:android:3634d1a29fa7b59fbed520',
    messagingSenderId: '650977751393',
    projectId: 'hediety-3d6a8',
    databaseURL: 'https://hediety-3d6a8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hediety-3d6a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi3eboqk0QouWy_yGGRVezbPJnxK1o3BE',
    appId: '1:650977751393:ios:5d23da483c3bfd63bed520',
    messagingSenderId: '650977751393',
    projectId: 'hediety-3d6a8',
    databaseURL: 'https://hediety-3d6a8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hediety-3d6a8.firebasestorage.app',
    iosBundleId: 'com.example.flutterGiftingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi3eboqk0QouWy_yGGRVezbPJnxK1o3BE',
    appId: '1:650977751393:ios:5d23da483c3bfd63bed520',
    messagingSenderId: '650977751393',
    projectId: 'hediety-3d6a8',
    databaseURL: 'https://hediety-3d6a8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hediety-3d6a8.firebasestorage.app',
    iosBundleId: 'com.example.flutterGiftingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDSUvHaAVlrbAt2xrRuS4G-9wZbmXj-uE',
    appId: '1:650977751393:web:910498e3b7f7cbfebed520',
    messagingSenderId: '650977751393',
    projectId: 'hediety-3d6a8',
    authDomain: 'hediety-3d6a8.firebaseapp.com',
    databaseURL: 'https://hediety-3d6a8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hediety-3d6a8.firebasestorage.app',
  );
}
